Format markdown in description
beam-community/elixir-companies pull request #676
Opened 2023-03-09 17:16 UTC by vvuunnqq

+ Fix: format markdown in description
+ Fix: infinite scroll too early

2023-03-09 17:17 UTC, vvuunnqq commented
result on my local machine
![image](https://user-images.githubusercontent.com/94352675/224104919-72c904cb-615c-46b0-b43c-ed5364756d0c.png)

2023-03-09 19:59 UTC, doomspork requested changes
Thank you again @vvuunnqq! 🎉 Small piece of feedback to keep our code consistent with the styleguide I try to align with (and configure Credo for).

2023-03-09 19:59 UTC, doomspork commented on lib/companies_web/views/company_view.ex
> +    |> Phoenix.HTML.raw()
I've been trying to keep the codebase as closely aligned to the community styleguide as possible: https://github.com/christopheradams/elixir_style_guide#avoid-single-pipelines

```suggestion
    markdown
    |> Earmark.as_html!()
    |> Phoenix.HTML.raw()
```

2023-03-09 23:26 UTC, vvuunnqq commented
Thanks, I updated

2023-03-10 15:32 UTC, doomspork approved these changes
You're the best @vvuunnqq! 🚀

2023-03-10 15:32 UTC, merged